development:
  db_filename: development.db
  redirect_url: "http://zinergia.com"
  admin_username: admin
  admin_password: my_super_secret_password
  domains:
    - colombiaaprende.edu.co
    - eafit.edu.co
    - localhost
  
production:
  db_filename: production.db
  redirect_url: "http://newton.eafit.edu.co"
  admin_username: admin
  admin_password: mysupersecretpassword
  domains:
    - nhocki.com
    - colombiaaprende.edu.co
    - eafit.edu.co
    - localhost